### ISSUE TITLE
Dependency pinning

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/jupyter-math#17]
Not all important packages are pinned in jupyter-math. We need to identify very important packages and at least pin those.

I have pinned jupyterlab https://github.com/ITISFoundation/jupyter-math/commit/b68245c6336dbe480e9c21915611136496bddf66

The following should for sure be pinned somehow. But we might want some input here from @colinRawlings since he had more to deal with dependencies of jupyters.

```
ipyevents              2.0.1
ipykernel              6.15.1
ipympl                 0.8.8
ipython                8.4.0
ipython-genutils       0.2.0
ipywidgets             7.7.0
```

Dependencies of the current most used version of math: [deps-2.0.8.txt](https://github.com/ITISFoundation/jupyter-math/files/11497089/deps-2.0.8.txt)

Dependencies from the last build of math (from my dev machine): [latest_build.txt](https://github.com/ITISFoundation/jupyter-math/files/11497099/latest_build.txt)

**Comment by colinRawlings** [comment]
Something has gotten a bit confused here, this repo is not implementing the workflow for [`pip-tools`](https://github.com/jazzband/pip-tools).  In particular:
- We should not be running `pip-compile` in the Dockerfile: https://github.com/ITISFoundation/jupyter-math/blob/739af55e9c1080498ccec871b7af9dbad6c6e026/Dockerfile#L68
- We should not be pinning the dependencies in the `.in` file.
- We should be using the `--resolver=backtracking` arg in the call to `pip-compile`
- We should have a target in the `Makefile` for updating the `requirements.txt` (and the results should be tracked with git).

Last time `jupyter-smash` was updated it correctly identified versions of` jupyer(lab)`, `ipyevents`, `ipywidgets` and `voila` that worked together without requiring manual intervention in the `.in` file:

https://git.speag.com/oSparc/services/jupyter-smash/-/blob/master/requirements/_base.txt
