### ISSUE TITLE
Allow agg backend for plots

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/jupyter-math#3]
From Newton

**Describe the goal**
(KZ: I assume this was done within the JupyterLab octave+python) I tried to generate a plot from within ipython in a console session (using the 'agg' backend), but failed to produce an image.

**Comment by elisabettai** [comment]
@newton1985, that's quite an old issue. Is it still a problem you have with the new JupyterLabs?

**Comment by newton1985** [comment]
no you can close it 👍
